//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.mu10
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// S33.
    /// </summary>
    //  *** Start programmer edit section *** (S33 CustomAttributes)

    //  *** End programmer edit section *** (S33 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("S33E", new string[0])]
    [View("S33L", new string[0])]
    public class S33 : ICSSoft.STORMNET.DataObject
    {
        
        //  *** Start programmer edit section *** (S33 CustomMembers)

        //  *** End programmer edit section *** (S33 CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "S33E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View S33E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("S33E", typeof(IIS.mu10.S33));
                }
            }
            
            /// <summary>
            /// "S33L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View S33L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("S33L", typeof(IIS.mu10.S33));
                }
            }
        }
    }
}
